# Generated by Django 3.2 on 2022-09-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0005_car_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['name'], 'verbose_name_plural': 'oxen'},
        ),
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterModelTable(
            name='car',
            table='cars',
        ),
    ]
