# Generated by Django 3.2 on 2022-09-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0006_auto_20220920_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, null=True)),
                ('age', models.DateField(null=True)),
                ('home_group', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'students_info',
            },
        ),
    ]
