# Generated by Django 4.0.7 on 2023-04-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0005_place_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='serves_pizza',
            field=models.BooleanField(default=False, help_text='Please use the following format <em>YYYY-MM-DD</em>'),
        ),
    ]
