# Generated by Django 4.0.7 on 2023-04-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0006_alter_restaurant_serves_pizza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='serves_pizza',
            field=models.BooleanField(default=False, help_text='Sample <em>help</em> text'),
        ),
    ]
