# Generated by Django 4.0.7 on 2023-04-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0007_alter_restaurant_serves_pizza'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['name', 'address'], name='practice_pl_name_e0d53b_idx'),
        ),
    ]
