# Generated by Django 4.0.7 on 2023-04-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0008_place_practice_pl_name_e0d53b_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='place',
            name='practice_pl_name_e0d53b_idx',
        ),
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['first_name', 'last_name'], name='practice_pe_first_n_e4eb3e_idx'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.CheckConstraint(check=models.Q(('age__lt', 18)), name='age_constraint'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('email',), name='Email must be unique'),
        ),
    ]
