# Generated by Django 4.0.7 on 2023-04-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0009_remove_place_practice_pl_name_e0d53b_idx_person_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=50, unique=True),
        ),
    ]
