# Generated by Django 4.0.7 on 2023-04-25 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0012_remove_person_age_constraint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
    ]
